### ISSUE TITLE
Intel SGX DKMS driver doesn't compile on the latest Ubuntu 18.04.3 LTS with kernel 5.0

### ISSUE THREAD

**Issue by tjanez** [fortanix/rust-sgx#168]
Ubuntu has released the [18.04.3 LTS point release on Aug 19, 2019](https://www.omgubuntu.co.uk/2019/08/ubuntu-18-04-3-point-release).

Among other updates, it [includes kernel 5.0](https://www.omgubuntu.co.uk/2019/08/ubuntu-18-04-3-point-release).

After the upgrade, the Fortanix-provided `intel-sgx-dkms` package doesn't compile the SGX module anymore.

The contents of of `/var/crash/intel-sgx-dkms.0.crash` is:
```
ProblemType: Package
DKMSBuildLog:
 DKMS make.log for intel-sgx-1.9 for kernel 5.0.0-1014-azure (x86_64)
 Thu Aug 22 12:37:25 UTC 2019
 make: Entering directory '/usr/src/linux-headers-5.0.0-1014-azure'
   CC [M]  /var/lib/dkms/intel-sgx/1.9/build/sgx_main.o
   CC [M]  /var/lib/dkms/intel-sgx/1.9/build/sgx_page_cache.o
   CC [M]  /var/lib/dkms/intel-sgx/1.9/build/sgx_ioctl.o
   CC [M]  /var/lib/dkms/intel-sgx/1.9/build/sgx_vma.o
 /var/lib/dkms/intel-sgx/1.9/build/sgx_ioctl.c: In function 'sgx_process_add_page_req':
 /var/lib/dkms/intel-sgx/1.9/build/sgx_ioctl.c:251:8: error: implicit declaration of function 'vm_insert_pfn'; did you mean 'vmf_insert_pfn'? [-Werror=implicit-function-declaration]
   ret = vm_insert_pfn(vma, encl_page->addr, PFN_DOWN(epc_page->pa));
         ^~~~~~~~~~~~~
         vmf_insert_pfn
   CC [M]  /var/lib/dkms/intel-sgx/1.9/build/sgx_util.o
 cc1: some warnings being treated as errors
 scripts/Makefile.build:284: recipe for target '/var/lib/dkms/intel-sgx/1.9/build/sgx_ioctl.o' failed
 make[1]: *** [/var/lib/dkms/intel-sgx/1.9/build/sgx_ioctl.o] Error 1
 make[1]: *** Waiting for unfinished jobs....
 /var/lib/dkms/intel-sgx/1.9/build/sgx_util.c: In function 'sgx_do_fault':
 /var/lib/dkms/intel-sgx/1.9/build/sgx_util.c:352:7: error: implicit declaration of function 'vm_insert_pfn'; did you mean 'vmf_insert_pfn'? [-Werror=implicit-function-declaration]
   rc = vm_insert_pfn(vma, entry->addr, PFN_DOWN(entry->epc_page->pa));
        ^~~~~~~~~~~~~
        vmf_insert_pfn
 cc1: some warnings being treated as errors
 scripts/Makefile.build:284: recipe for target '/var/lib/dkms/intel-sgx/1.9/build/sgx_util.o' failed
 make[1]: *** [/var/lib/dkms/intel-sgx/1.9/build/sgx_util.o] Error 1
 Makefile:1606: recipe for target '_module_/var/lib/dkms/intel-sgx/1.9/build' failed
 make: *** [_module_/var/lib/dkms/intel-sgx/1.9/build] Error 2
 make: Leaving directory '/usr/src/linux-headers-5.0.0-1014-azure'
DKMSKernelVersion: 5.0.0-1014-azure
Date: Thu Aug 22 12:37:31 2019
DuplicateSignature: dkms:intel-sgx-dkms:1.9-2:/var/lib/dkms/intel-sgx/1.9/build/sgx_ioctl.c:251:8: error: implicit declaration of function 'vm_insert_pfn'; did you mean 'vmf_insert_pfn'? [-Werror=implicit-function-declaration]
Package: intel-sgx-dkms 1.9-2
PackageVersion: 1.9-2
SourcePackage: intel-sgx-dkms
Title: intel-sgx-dkms 1.9-2: intel-sgx kernel module failed to build
```

---

It looks like the [upstream `linux-sgx-driver` repository](https://github.com/intel/linux-sgx-driver/) already contains the fix:
https://github.com/intel/linux-sgx-driver/commit/d617da1c721fb7023889bc791e34f117668464ff.

The current version of `intel-sgx-dkms` package is:
```
# dpkg -s intel-sgx-dkms
Package: intel-sgx-dkms
Status: install ok installed
Priority: optional
Section: kernel
Installed-Size: 105
Maintainer: Andy Leiserson <andy@fortanix.com>
Architecture: amd64
Version: 1.9-2
Depends: dkms (>= 2.1.1.1)
Description: Intel SGX kernel module for Linux
```

Would you consider updating the `intel-sgx-dkms` package?

**Comment by tjanez** [comment]
> We're planning on updating to the 2.5 driver soon

Great, thanks for the info!

**Comment by tjanez** [comment]
@jethrogb, any update on this one?

**Comment by jethrogb** [comment]
I believe 2.11 was released some time ago?
