### ISSUE TITLE
enclave-runner: Compile error on 1.87

### ISSUE THREAD

**Issue by DragonDev1906** [fortanix/rust-sgx#765]
Projects that use `enclave-runner` currently do not compile on Rust version 1.87 (stable) or beta.

```bash
cargo new sgx-never-type
cd sgx-never-type
cargo add enclave-runner
cargo +1.87 check
```

This does compile with `1.86` and lower. [^1]

[^1]: Which is weird because the eror is about the `!` type, which wasn't a stable feature in 1.86 either.

Note that checking/compiling within this repo doesn't result in this error for some reason: `cargo +1.87 check -p enclave-runner`, I don't know why.

```
    Checking enclave-runner v0.7.0
error[E0658]: the `!` type is experimental
   --> /home/jens/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/enclave-runner-0.7.0/src/usercalls/abi.rs:311:1
    |
311 | invoke_with_usercalls!(define_usercalls);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #35121 <https://github.com/rust-lang/rust/issues/35121> for more information
    = note: this error originates in the macro `invoke_with_usercalls` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `!: RegisterArgument` is not satisfied
   --> /home/jens/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/enclave-runner-0.7.0/src/usercalls/abi.rs:64:59
    |
64  |                     (handler, ReturnValue::into_registers(ret))
    |                               --------------------------- ^^^ the trait `RegisterArgument` is not implemented for `!`
    |                               |
    |                               required by a bound introduced by this call
...
311 | invoke_with_usercalls!(define_usercalls);
    | ---------------------------------------- in this macro invocation
    |
    = help: the following other types implement trait `RegisterArgument`:
              ()
              *const T
              *mut T
              Option<NonNull<T>>
              bool
              i16
              i32
              i64
            and 7 others
note: required for `std::result::Result<!, usercalls::EnclaveAbort<bool>>` to implement `ReturnValue`
   --> /home/jens/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/enclave-runner-0.7.0/src/usercalls/abi.rs:162:27
    |
162 | impl<T: RegisterArgument> ReturnValue for UsercallResult<T> {
    |         ----------------  ^^^^^^^^^^^     ^^^^^^^^^^^^^^^^^
    |         |
    |         unsatisfied trait bound introduced here
    = note: this error originates in the macro `define_usercalls` which comes from the expansion of the macro `invoke_with_usercalls` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0053]: method `exit` has an incompatible type for trait
   --> /home/jens/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/enclave-runner-0.7.0/src/usercalls/interface.rs:189:10
    |
189 |     ) -> std::pin::Pin<Box<dyn Future<Output = (Self, EnclaveAbort<bool>)> + 'future>> {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<!, EnclaveAbort<bool>>`, found `usercalls::EnclaveAbort<bool>`
    |
note: type in trait
   --> /home/jens/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/enclave-runner-0.7.0/src/usercalls/abi.rs:177:17
    |
177 |                 std::pin::Pin<Box<dyn Future<Output = (Self, UsercallResult<$r>)> + $l>>
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
311 | invoke_with_usercalls!(define_usercalls);
    | ---------------------------------------- in this macro invocation
    = note: expected signature `fn(interface::Handler<'_, '_>, _) -> Pin<Box<(dyn futures::Future<Output = (interface::Handler<'ioinput, 'tcs>, std::result::Result<!, usercalls::EnclaveAbort<bool>>)> + 'future)>>`
               found signature `fn(interface::Handler<'_, '_>, _) -> Pin<Box<(dyn futures::Future<Output = (interface::Handler<'ioinput, 'tcs>, usercalls::EnclaveAbort<bool>)> + 'future)>>`
    = note: this error originates in the macro `dispatch_return_type` which comes from the expansion of the macro `invoke_with_usercalls` (in Nightly builds, run with -Z macro-backtrace for more info)
help: change the output type to match the trait
    |
189 -     ) -> std::pin::Pin<Box<dyn Future<Output = (Self, EnclaveAbort<bool>)> + 'future>> {
189 +     ) -> Pin<Box<(dyn futures::Future<Output = (interface::Handler<'ioinput, 'tcs>, std::result::Result<!, usercalls::EnclaveAbort<bool>>)> + 'future)>> {
    |

Some errors have detailed explanations: E0053, E0277, E0658.
For more information about an error, try `rustc --explain E0053`.
error: could not compile `enclave-runner` (lib) due to 3 previous errors
```

**Comment by jethrogb** [comment]
This is fixed in #749 which hasn't been published yet
